apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homepage-kustomization

commonLabels:
  app: homepage

resources:
  - deployment.yaml
  - persistent-volume-claim.yaml
  - service.yaml
